# Tmux Configuration

# -- Basic Settings ------------------------------------------
set -g prefix C-Space
set -g escape-time 500
set -g history-limit 5000
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on

# -- Key Bindings ------------------------------------------
unbind s

# Session management
bind Space display-popup -E "tms switch"
bind C-c display-popup -E "tms" # create new tms session
bind C-r command-prompt -p "Rename active session to: " "run-shell 'tms rename %1'".

# Window management
bind C-Space display-popup -E "tms windows"
bind C-x confirm -p "Kill current session? (y/N):" "run-shell 'tms kill'"

# Pane management
bind - split-window -v
bind \\ split-window -h

unbind q
bind q display-popup -E "nvim ~/notes/quick.md"

# -- Plugins -----------------------------------------------
# Plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Other plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'niksingh710/minimal-tmux-status'

# Initialize TMUX plugin manager
# Keep this line at the very bottom of tmux.conf
run '~/.config/tmux/plugins/tpm/tpm'
