apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: reflector-repo
  pass_credentials_all: false
  password: ""
  url: https://emberstack.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nats-repo
  pass_credentials_all: false
  password: ""
  url: https://nats-io.github.io/k8s/helm/charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cnpg-repo
  pass_credentials_all: false
  password: ""
  url: https://cloudnative-pg.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jetstack-repo
  pass_credentials_all: false
  password: ""
  url: https://charts.jetstack.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: authentik-repo
  pass_credentials_all: false
  password: ""
  url: https://charts.goauthentik.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: seaweed-repo
  pass_credentials_all: false
  password: ""
  url: https://seaweedfs.github.io/seaweedfs/helm
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: traefik-repo
  pass_credentials_all: false
  password: ""
  url: https://helm.traefik.io/traefik
  username: ""
